[build]
builder = "NIXPACKS"
buildCommand = "npm install --legacy-peer-deps && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[deploy.envs]
NODE_ENV = "production"
NODE_VERSION = "18.19.0"
NPM_VERSION = "10.2.3"
NPM_CONFIG_LEGACY_PEER_DEPS = "true" 